language: python

python:
  - "3.6"

install: pip install -r requirements.txt

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script: python Phanteks/main.py

services:
  - MongoDB