language: python

python:
  - "3.6"

install: pip install -r requirements.txt

#before_script:
#  - sleep 15
#  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
 - python3 Phanteks/getProductData_cn.py
 - python3 NZXT/getProductData_cn.py

#services:
#  - MongoDB